<?php

/**
 * @file
 * Configuration module for Islandora Solr Geo.
 */

/**
 * Implements hook_menu().
 */
function islandora_solr_geo_menu() {
  $items = array();
  $items['admin/islandora/search/islandora_solr_geo'] = array(
    'title' => 'Islandora Solr Geo Administration',
    'type' => MENU_CALLBACK,
    'weight' => 5,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_geo_admin_form'),
    'access arguments' => array('administer islandora solr'),
    'file' => 'includes/admin.inc',
  );
  return $items;
}

/**
 * Implements hook_islandora_solr_primary_display().
 */
function islandora_solr_geo_islandora_solr_primary_display() {
  return array(
    'geo' => array(
      'name' => t('Map'),
      'module' => 'islandora_solr_geo',
      'file' => 'includes/geo_results.inc',
      'class' => "IslandoraSolrResultsGeo",
      'function' => "displayResults",
      'description' => t("Display search results on a map"),
      'configuration' => 'admin/islandora/search/islandora_solr_geo',
    ),
  );
}

/**
 * Implements hook_islandora_solr_query().
 *
 * Takes the current results limit (admin default or from url parameter) and
 * finds the closed number that is dividable by 4 and 3, so when the layout is
 * sized down in a responsive layout, the last row of results won't show
 * 'trailing' results.
 */
function islandora_solr_geo_islandora_solr_query($islandora_solr_query) {
  // We're dealing with the geo display.
  if ($islandora_solr_query->display == 'geo') {
    // More changes here could be made such as modifying the solrLimit as well
    // as modifying the query etc.
    $coordinate_field = variable_get('islandora_solr_geo_coordinates_field', 'mods_subject_cartographics_coordinates_ms');
    $islandora_solr_query->solrParams['fq'][] = "$coordinate_field:*";
  }
}

/**
 * Implements hook_theme().
 */
function islandora_solr_geo_theme() {
  $path = drupal_get_path('module', 'islandora_solr_geo');
  return array(
    'islandora_solr_geo_display_results' => array(
      'path' => "$path/theme",
      'file' => 'theme.inc',
      'template' => 'islandora-solr-geo-display-results',
      'variables' => array(
        'results' => NULL,
      ),
    ),
    'islandora_solr_geo_balloon' => array(
      'path' => "$path/theme",
      'file' => 'theme.inc',
      'template' => 'islandora-solr-geo-balloon',
      'variables' => array(
        'solr_result' => NULL,
      ),
    ),
  );
}
/**
 * Helper class to work with ip_geoloc module.
 */
class IslandoraMapObjectLocation {
  /**
   * Constructor for the helper map object.
   *
   * @param NULL|string $marker_color
   *   The color of the marker or NULL if we are not specifying one.
   * @param NULL|string $lat
   *   The latitude of the co-ordinate we are rendering or NULL.
   * @param NULL|string $long
   *   The longitude of the co-ordinate we are rendering or NULL.
   * @param NULL|string $balloon_text
   *   The markup for the balloon or NULL.
   */
  public function __construct($marker_color = NULL, $lat = NULL, $long = NULL, $balloon_text = '') {
    $this->marker_color = $marker_color;
    $this->latitude = $lat;
    $this->longitude = $long;
    $this->balloon_text = $balloon_text;
  }
}
