<?php

/**
 * @file
 * Configuration module for Islandora Solr.
 */

/**
 * Implements hook_islandora_solr_primary_display().
 */
function islandora_solr_config_islandora_solr_primary_display() {
  return array(
    // 'machien-name' = array(
    //   'name' => 'Human Readable Name',
    //   'module' => 'module_name',
    //   'file' => 'FileName.inc',
    //   'class' => 'ClassName',
    //   'function' => 'function_name',
    //   'description' => 'A description of the display profile',
    // );
    'grid' => array(
      'name' => t('Grid'),
      'module' => 'islandora_solr_config',
      'file' => 'includes/grid_results.inc',
      'class' => "IslandoraSolrResultsGrid",
      'function' => "displayResults",
      'description' => t("Search results as a grid view"),
    ),
    'table' => array(
      'name' => t('Table'),
      'module' => 'islandora_solr_config',
      'file' => 'includes/table_results.inc',
      'class' => "IslandoraSolrResultsTable",
      'function' => "displayResults",
      'description' => t("Search results as tabular output"),
    ),
  );
}

/**
 * Implements hook_islandora_solr_secondary_display().
 */
function islandora_solr_config_islandora_solr_secondary_display() {
  // set path
  global $base_path;
  $path = $base_path . drupal_get_path('module', 'islandora_solr_config');
  return array(
    'csv' => array(
      'name' => t('CSV'),
      'module' => 'islandora_solr_config',
      'file' => 'includes/csv_results.inc',
      'class' => 'IslandoraSolrResultsCSV',
      'function' => 'printCSV',
      'description' => 'Download complete resultset as a CSV Spreadsheet',
      'logo' => '<img src="' . $path . '/images/csv.png" class="secondary-display-csv">',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_solr_config_theme() {
  // set path
  $path = drupal_get_path('module', 'islandora_solr_config');

  return array(
    // grid results display
    'islandora_solr_grid' => array(
      'path' => $path . '/theme',
      'template' => 'islandora-solr-grid',
      'variables' => array('results' => NULL, 'elements' => array()),
    ),
    // table results display
    'islandora_solr_table' => array(
      'path' => $path . '/theme',
      'template' => 'islandora-solr-table',
      'variables' => array('header' => NULL, 'rows' => NULL, 'elements' => array()),
    ),
  );
}

/**
 * Implements hook_islandora_solr_query().
 *
 * Takes the current results limit (admin default or from url parameter) and
 * finds the closed number that is dividable by 4 and 3, so when the layout is
 * sized down in a responsive layout, the last row of results won't show
 * 'trailing' results.
 *
 * @param object $islandora_solr_query
 *   The IslandoraSolrQueryProcessor object which includes the current query
 *   settings but at the beginning of IslandoraSolrQueryProcessor::executeQuery().
 */
function islandora_solr_config_islandora_solr_query($islandora_solr_query) {

  // we're dealing with the grid display
  if ($islandora_solr_query->display == 'grid') {

    // set results limit
    $limit = $islandora_solr_query->solrLimit;

    // not dividable yet
    $dividable = FALSE;
    while ($dividable == FALSE) {
      // dividable by 4 and 3
      if (($limit % 4) == 0 && ($limit % 3) == 0) {
        $dividable = TRUE;
        $solr_limit = $limit;
      }
      $limit++;
    }
    // set new limit
    $islandora_solr_query->solrLimit = $solr_limit;
  }
}